### ISSUE TITLE
Finding Keys on Windows

### ISSUE THREAD

**Issue by Schlitzohr101** [proglottis/gpgme#16]
I have an error where the gpgme.FindKeys does not work as expected on windows. Any help on this would be appreciated. If there is more information that i can give to help, just let me know

**Comment by monirz** [comment]
@proglottis Any thoughts on that we are using this function `gpgme.FindKeys("", false)` to detect all the keys  from the system and it worked as expected on Linux. But on Windows it does not work instead it throws and error something like `unsupported protocol`. We have tried few version GnuPG for Windows and it seems to be we have been able to install or generate the keys in standard location. Or apart from this can we detect the keys from a file just providing the file path? Thank you.

**Comment by proglottis** [comment]
I haven't tested much in windows at all. #14 is the long standing issue for windows build issues

I think you might be best to check GetEngineInfo and see if all the paths are sensible, set them to what you expect with SetEngineInfo if not. You can use this to tell gpg where your keyring files are

**Comment by monirz** [comment]
That is useful, I think that would work as per our requirement. Thank you!
