### ISSUE TITLE
Does not build on Travis-CI [Linux]

### ISSUE THREAD

**Issue by keltia** [proglottis/gpgme#17]
When I try to build gpgme for my module running on Travis-CI for continuous integration, I get these (maybe cgo-related) errors:

```
go: downloading github.com/proglottis/gpgme v0.0.0-20170426024346-49ea2555b6fc
go: downloading golang.org/x/text v0.3.0
golang_org/x/crypto/cryptobyte/asn1
github.com/BurntSushi/toml
github.com/pkg/errors
github.com/proglottis/gpgme
golang_org/x/crypto/cryptobyte
golang_org/x/net/dns/dnsmessage
net
# github.com/proglottis/gpgme
../../../../pkg/mod/github.com/proglottis/gpgme@v0.0.0-20170426024346-49ea2555b6fc/gpgme.go:72:35: could not determine kind of name for C.GPGME_ENCRYPT_NO_COMPRESS
../../../../pkg/mod/github.com/proglottis/gpgme@v0.0.0-20170426024346-49ea2555b6fc/gpgme.go:556:38: could not determine kind of name for C.GPGME_EXPORT_MODE_PKCS12
../../../../pkg/mod/github.com/proglottis/gpgme@v0.0.0-20170426024346-49ea2555b6fc/gpgme.go:555:38: could not determine kind of name for C.GPGME_EXPORT_MODE_RAW
../../../../pkg/mod/github.com/proglottis/gpgme@v0.0.0-20170426024346-49ea2555b6fc/gpgme.go:554:38: could not determine kind of name for C.GPGME_EXPORT_MODE_SECRET
../../../../pkg/mod/github.com/proglottis/gpgme@v0.0.0-20170426024346-49ea2555b6fc/gpgme.go:86:40: could not determine kind of name for C.GPGME_KEYLIST_MODE_WITH_SECRET
../../../../pkg/mod/github.com/proglottis/gpgme@v0.0.0-20170426024346-49ea2555b6fc/gpgme.go:50:30: could not determine kind of name for C.GPGME_PROTOCOL_SPAWN
golang_org/x/crypto/internal/chacha20
```

Not sure how to fix these.

**Comment by proglottis** [comment]
Thanks for the report. The build normally complains about constants if the gpgme version isn't exactly matched. I haven't decided quite how to solve this yet. I've had #15 open for some time for the same reason, quite tricky with apt to get a good modern version of gpgme that will run all the tests and has all the constants.

This may have changed now. I haven't checked for a while

**Comment by keltia** [comment]
Thanks.  It was difficult enough to get the right packages on Travis but I might have different version than expected.  This is what I use: https://github.com/keltia/archive/blob/master/.travis.yml

**Comment by proglottis** [comment]
@keltia I've decided to break backwards compat here and remove the constants that are newer than what a typical linux install gets. This repo now has a travis build that at least works on linux/osx

**Comment by keltia** [comment]
Thanks!  Will test and report.
