### ISSUE TITLE
tag official releases

### ISSUE THREAD

**Issue by anarcat** [proglottis/gpgme#19]
hi,

first, thank you for this software, it looks quite useful and is used in a tool I am packaging for debian ([dmarc-cat](https://github.com/keltia/dmarc-cat/)).

one problem with this dependency is that it doesn't have official releases. it makes it hard to find out when changes happen in the code base. it also makes tracking module dependencies with the new golang module system harder.

would you consider using official, tagged releases for your software?

again thank you for your time.

**Comment by anarcat** [comment]
ping?

**Comment by proglottis** [comment]
Thanks for bearing with me @anarcat 

I've tagged release v0.1.0 now
