### ISSUE TITLE
Decrypt test fails with "No Data".

### ISSUE THREAD

**Issue by keltia** [proglottis/gpgme#20]
Hello, I have a module (https://github.com/keltia/archive) which encapsulate various "archive" formats including gpg encrypted (so I use it as a wrapper in my other modules).  I used it in a tool which decrypt and extract CERT-EU files (https://github.com/keltia/erc-cimbl).  It has stopped working a while ago and I have to decrypt manually now.

While looking at the issue in my `archive` module, I find that `gpgme` has a failing test with exactly the same message `No Data`.  Can you please investigate?

There are other failing tests but they are less of an issue (especially  the last one as it is a local problem).

<pre>
=== RUN   TestNewData
--- PASS: TestNewData (0.00s)
=== RUN   TestNewDataBytes
--- PASS: TestNewDataBytes (0.00s)
=== RUN   TestDataNewDataFile
--- PASS: TestDataNewDataFile (0.00s)
=== RUN   TestDataNewDataReader
--- PASS: TestDataNewDataReader (0.00s)
=== RUN   TestDataNewDataWriter
--- PASS: TestDataNewDataWriter (0.00s)
=== RUN   TestEngineInfo
--- PASS: TestEngineInfo (0.07s)
=== RUN   TestContext_Armor
--- PASS: TestContext_Armor (0.00s)
=== RUN   TestContext_TextMode
--- PASS: TestContext_TextMode (0.00s)
=== RUN   TestContext_EngineInfo
--- PASS: TestContext_EngineInfo (0.01s)
=== RUN   TestContext_Encrypt
--- FAIL: TestContext_Encrypt (0.01s)
    gpgme_test.go:184: Invalid value
=== RUN   TestContext_Decrypt
--- FAIL: TestContext_Decrypt (0.01s)
    gpgme_test.go:198: No data
=== RUN   TestContext_DecryptVerify
--- FAIL: TestContext_DecryptVerify (0.01s)
    gpgme_test.go:210: No data
=== RUN   TestContext_Sign
--- FAIL: TestContext_Sign (0.02s)
    gpgme_test.go:218: key "test@example.com" not found
=== RUN   TestContext_Verify
--- FAIL: TestContext_Verify (0.02s)
    gpgme_test.go:238: key "test@example.com" not found
=== RUN   TestContext_Import
--- FAIL: TestContext_Import (0.02s)
    gpgme_test.go:315: Unexpected import result field Considered, value 0, expected 1
    gpgme_test.go:315: Unexpected import result field Imported, value 0, expected 1
    gpgme_test.go:324: Unexpected number of import status values 0
=== RUN   TestContext_Export
--- FAIL: TestContext_Export (0.01s)
    gpgme_test.go:344: Expected exported keys, got empty buffer
=== RUN   TestContext_AssuanSend
dyld: Library not loaded: /opt/local/lib/libreadline.6.dylib
  Referenced from: /opt/local/bin/gpg-connect-agent
  Reason: image not found
--- SKIP: TestContext_AssuanSend (0.02s)
    gpgme_test.go:355: signal: abort trap
FAIL
FAIL	github.com/proglottis/gpgme	0.196s
<pre>

**Comment by proglottis** [comment]
This "No data" error comes straight from gpgme - `GPG_ERR_NO_DATA` https://www.gnupg.org/documentation/manuals/gpgme/Decrypt.html

> GPG_ERR_NO_DATA if cipher does not contain any data to decrypt

I think this error message is probably misleading as these tests use their own keyring and definitely pass in data to decrypt.

I searched around a little and it seems to be a pretty common error message from gpgme but I'm not very familiar with it sorry. It's interesting that the `Data` tests are passing on their own, but no encryption/decryption or even export/import. The encryption error you get `GPG_ERR_INV_VALUE` https://www.gnupg.org/documentation/manuals/gpgme/Encrypting-a-Plaintext.html

> GPG_ERR_INV_VALUE if ctx, recp, plain or cipher is not a valid pointer

**Comment by keltia** [comment]
Ok but the thing is, gpg can decrypt that file just fine :(

**Comment by proglottis** [comment]
The tests do a wee bit of mucking around to try find the correct GPG binary to use (because some tests only work with gpg1). So maybe that's causing issues.

Maybe try run something like this and see if the binary location are what you'd expect https://play.golang.org/p/O-KodNjKXgi

**Comment by keltia** [comment]
And it is not what I expected to thanks for the hint and `GetEngineInfo()`.  I have indeed a broken gpg binary lying around.  I'll check and close the issue if this is what I think.

**Comment by mccormick-wooden** [comment]
Hi @keltia , wondering if you ever resolved this issue. I'm encountering a very similar issue where I'm able to decrypt a file just fine using `gpg` CLI, but using `gpgme` on the exact same file results in this `NoData` error. It's very perplexing.
