### ISSUE TITLE
macOS `fatal error: 'gpgme.h' file not found`

### ISSUE THREAD

**Issue by kaovilai** [proglottis/gpgme#32]
I'm consuming a library at github.com/containers/image.. specifically this go module
github.com/containers/image/v5@v5.21.1 
requires
github.com/proglottis/gpgme@v0.1.1

and it's causing my go tests to fail.

```
go test ./... -coverprofile cover.out
# github.com/proglottis/gpgme
../../go/pkg/mod/github.com/proglottis/gpgme@v0.1.1/data.go:4:11: fatal error: 'gpgme.h' file not found
```

It would be cool if you could include suggested solutions for getting this library installed in different OSes.

Maybe link to https://www.gnupg.org/download/index.html

For macos, one might use homebrew `brew install gpgme`.

You may also have package managers such as `apt`, `dnf`, or `yum` for your OS which contain may gpgme package.

**Comment by proglottis** [comment]
FWIW this is documented on `image` https://github.com/containers/image#building

I'd be happy for any docs contributions.

**Comment by kaovilai** [comment]
unfortunately still stuck at https://github.com/proglottis/gpgme/issues/33
