### ISSUE TITLE
lb: library not found for -lassuan

### ISSUE THREAD

**Issue by sylvek** [proglottis/gpgme#33]
✋ I'm trying to rewrite my personal project (https://github.com/sylvek/leeloo) in Go. I found your library 🙏 but sadely, when i did a stupid test of encryption, i have this error

```
github.com/proglottis/gpgme
# github.com/proglottis/gpgme
ld: library not found for -lassuan
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm on MacOS M1 and my own project already uses "gpgme".. so i assume it is installed fine.

Do you have any idea to fix this issue? 🤔

**Comment by kaovilai** [comment]
My current workaround is https://gitpod.io/

**Comment by proglottis** [comment]
@sylvek It should work on macos though I've never used M1. I've even setup a macos workflow https://github.com/proglottis/gpgme/blob/master/.github/workflows/go.yml#L41

I wonder if your gpgme is unlinked or something? Sorry I can't be more specific as I don't have macos right now.

**Comment by kaovilai** [comment]
Could try install `libassuan` as well but didn't work for me.

`brew install gpgme libassuan`

**Comment by sylvek** [comment]
> My current workaround is https://gitpod.io/

Sorry @kaovilai i didn'yt understand what your link could help 🤔

**Comment by sylvek** [comment]
@proglottis is it possible that the issue is coming from the version of gnupg?

▶ brew info gnupg

```
gnupg: stable 2.3.6 (bottled)
GNU Pretty Good Privacy (PGP) package
https://gnupg.org/
/opt/homebrew/Cellar/gnupg/2.3.6 (149 files, 13.6MB) *
  Poured from bottle on 2022-04-27 at 16:41:13
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gnupg.rb
License: GPL-3.0-or-later
==> Dependencies
Build: pkg-config ✔
Required: gettext ✔, gnutls ✔, libassuan ✔, libgcrypt ✔, libgpg-error ✔, libksba ✔, libusb ✔, npth ✔, pinentry ✔
==> Analytics
install: 70,313 (30 days), 264,446 (90 days), 990,320 (365 days)
install-on-request: 66,918 (30 days), 249,849 (90 days), 931,477 (365 days)
build-error: 11 (30 days)
```

**Comment by kaovilai** [comment]
This might do something haven't tested yet. It's possible libassuan brew package currently doesn't install everything for aarch64.

https://www.wisdomgeek.com/development/installing-intel-based-packages-using-homebrew-on-the-m1-mac/#:~:text=Installing%20Homebrew%20on%20the%20M1%20mac%20was%20pretty,have%20a%20separate%20installation%20for%20the%20Rosetta%20emulator.

**Comment by kaovilai** [comment]
Maybe if this line can remove `-lassuan` we'd be good. https://github.com/proglottis/gpgme/blob/12c28f9249819fcebe8c050e0cbbe4c66543e186/gpgme.go#L5

**Comment by sylvek** [comment]
🤔 I removed `-lassuan` and `-lgpg-error` and it seems building.

```
// #cgo pkg-config: gpgme
// #cgo LDFLAGS: -lgpgme
```
I'll do more tests tomorrow.

**Comment by kaovilai** [comment]
@proglottis can you enlighten us why we need to link libassuan? can it be avoided?

**Comment by proglottis** [comment]
@sylvek @kaovilai thanks for investigating.

IIUC libassuan implements one of the protocols between gpg-agent and gpgme. This protocol is swappable, so it might be possible that your version has it compiled out.

I realised while you were removing things from `LD_FLAGS` that the reason it still works is probably because pkg-config is already setting these correctly. pkg-config is pretty new to this project https://github.com/proglottis/gpgme/pull/26 

So I think the fix is just to remove `LD_FLAGS` entirely and leave it to pkg-config which should know how gpgme was configured.

I've raised an MR https://github.com/proglottis/gpgme/pull/35 - Before I merge, would you be able to test that it works? Thanks!

**Comment by proglottis** [comment]
Thanks all. I've cut a release with the fix https://github.com/proglottis/gpgme/releases/tag/v0.1.3
